/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TricryptoLPGetter__factory } from "./TricryptoLPGetter__factory";
export { TricryptoStrategy__factory } from "./TricryptoStrategy__factory";
