/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ProxyONFT1155__factory } from "./ProxyONFT1155__factory";
export { ProxyONFT721__factory } from "./ProxyONFT721__factory";
export { UniversalONFT721__factory } from "./UniversalONFT721__factory";
