/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ARBTriCryptoOracle } from "./ARBTriCryptoOracle";
export type { GLPOracle } from "./GLPOracle";
